injectEnvironmentFiles:
  - .env?
  - .env.test?

nodeLinker: node-modules

npmScopes:
  datadog:
    npmRegistryServer: "https://registry.npmjs.org"
    npmPublishRegistry: "https://registry.npmjs.org"

npmRegistries:
  "https://registry.npmjs.org":
    npmAlwaysAuth: true
    npmAuthToken: "${NPM_PUBLISH_TOKEN}"
