injectEnvironmentFiles:
  - .env?
  - .env.test?

nodeLinker: node-modules

npmScopes:
  datadog:
    npmRegistryServer: "https://registry.npmjs.org"
    npmPublishRegistry: "https://registry.npmjs.org"
