name: CI - Verify Plugins
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  verify:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@85e6279cec87321a52edac9c87bce653a07cf6c2
    - name: Use Node.js 22.x with yarn cache
      uses: actions/setup-node@cdca7365b2dadb8aad0a33bc7601856ffabcc48e
      with:
        node-version: 22.x
        cache: yarn
    - name: Install Dependencies
      run: yarn install
    - name: Verify Plugins
      run: yarn verify