name: CI - Verify Plugins
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

jobs:
  verify:
    runs-on: ubuntu-latest
    steps:
      - name: checkout-code
        uses: actions/checkout@85e6279cec87321a52edac9c87bce653a07cf6c2
      - name: install-build-tools
        uses: jdx/mise-action@13abe502c30c1559a5c37dff303831bab82c9402
      - name: install-dependencies
        run: yarn install
      - name: verify-project
        run: yarn verify
