name: CI - Verify Plugins
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  verify:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@85e6279cec87321a52edac9c87bce653a07cf6c2
    - name: Use Node.js 22.x with yarn cache
      uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020
      with:
        node-version: 22.14.0
        cache: yarn
    - name: Install Dependencies
      run: yarn install
    - name: Verify Plugins
      run: yarn verify